#! /usr/bin/env bash

PREFIX=$1

install -v -m 644 bin/libmcl.a "$PREFIX/lib"
install -v -m 755 bin/clcc     "$PREFIX/bin"
install -v -m 755 bin/clcd     "$PREFIX/bin"
install -v -m 755 bin/clct     "$PREFIX/bin"

find include -type f \! -path '*.svn*' -exec install -v -m 644 "{}" -D "$PREFIX/{}" \;
